<a href="https://colab.research.google.com/github/HanyuWu/Computer-vision/blob/master/scatch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
class NearestNeighbor:
  def _inif_(self):
    pass
  
  def train(Self,X,y):
    self.Xtr = X
    self.ytr = y

In [11]:
t = np.zeros([5,5])
print(t)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
